let xquestions = [
    {
        "question": "Frage1: Berlin ist die Hauptstadt welchen Landes?",
        "answer_1": "Frankreich",
        "answer_2": "Spanien",
        "answer_3": "Deutschland",
        "answer_4": "Italien",
        "right_answer": "3"
    }
]

let myArray = []

const couples = [
["Berlin", "Deutschland", "de"],
["Paris", "Frankreich", "fr"],
["Madrid", "Spanien", "es"],
["Rom", "Italien", "it"],
["Wien", "Österreich", "at"],
["Bern", "Schweiz", "ch"],
["Amsterdam", "Niederlande", "nl"],
["Brüssel", "Belgien", "be"],
["Kopenhagen", "Dänemark", "dk"],
["Oslo", "Norwegen", "no"],
["Stockholm", "Schweden", "se"],
["Helsinki", "Finnland", "fi"],
["Athen", "Griechenland", "gr"],
["Lissabon", "Portugal", "pt"],
["Dublin", "Irland", "ie"],
["Prag", "Tschechien", "cz"],
["Warschau", "Polen", "pl"],
["Budapest", "Ungarn", "hu"],
["Sofia", "Bulgarien", "bg"],
["Bukarest", "Rumänien", "ro"],
["Zagreb", "Kroatien", "hr"],
["Sarajevo", "Bosnien und Herzegowina", "ba"],
["Belgrad", "Serbien", "rs"],
["Skopje", "Nordmazedonien", "mk"],
["Tirana", "Albanien", "al"],
["Podgorica", "Montenegro", "me"],
["Ljubljana", "Slowenien", "si"],
["Bratislava", "Slowakei", "sk"],
["Reykjavik", "Island", "is"],
["Tallinn", "Estland", "ee"],
["Riga", "Lettland", "lv"],
["Vilnius", "Litauen", "lt"],
["Valletta", "Malta", "mt"],
["London", "Vereinigtes Königreich", "gb"],
["Moskau", "Russland", "ru"],
["Kiew", "Ukraine", "ua"],
["Minsk", "Weißrussland", "by"],
["Ankara", "Türkei", "tr"],
["Washington D.C.", "USA", "us"],
["Ottawa", "Kanada", "ca"],
["Mexiko-Stadt", "Mexiko", "mx"],
["Brasília", "Brasilien", "br"],
["Buenos Aires", "Argentinien", "ar"],
["Santiago", "Chile", "cl"],
["Bogotá", "Kolumbien", "co"],
["Lima", "Peru", "pe"],
["Caracas", "Venezuela", "ve"],
["Canberra", "Australien", "au"],
["Wellington", "Neuseeland", "nz"],
["Peking", "China", "cn"],
["Neu-Delhi", "Indien", "in"],
["Tokio", "Japan", "jp"],
["Seoul", "Südkorea", "kr"],
["Bangkok", "Thailand", "th"],
["Jakarta", "Indonesien", "id"],
["Hanoi", "Vietnam", "vn"],
["Kuala Lumpur", "Malaysia", "my"],
["Singapur", "Singapur", "sg"],
["Manila", "Philippinen", "ph"],
["Riad", "Saudi-Arabien", "sa"],
["Abu Dhabi", "Vereinigte Arabische Emirate", "ae"],
["Doha", "Katar", "qa"],
["Teheran", "Iran", "ir"],
["Bagdad", "Irak", "iq"],
["Damaskus", "Syrien", "sy"],
["Amman", "Jordanien", "jo"],
["Kairo", "Ägypten", "eg"],
["Addis Abeba", "Äthiopien", "et"],
["Nairobi", "Kenia", "ke"],
["Pretoria", "Südafrika", "za"],
["Accra", "Ghana", "gh"],
["Dakar", "Senegal", "sn"],
["Algier", "Algerien", "dz"],
["Tunis", "Tunesien", "tn"],
["Rabat", "Marokko", "ma"],
["Tripolis", "Libyen", "ly"],
["Khartum", "Sudan", "sd"],
["Luanda", "Angola", "ao"],
["Kinshasa", "Demokratische Republik Kongo", "cd"],
["Harare", "Simbabwe", "zw"],
["Kampala", "Uganda", "ug"],
["Maputo", "Mosambik", "mz"],
["Antananarivo", "Madagaskar", "mg"],
["Suva", "Fidschi", "fj"],
["Port Moresby", "Papua-Neuguinea", "pg"],
["Nassau", "Bahamas", "bs"],
["Havanna", "Kuba", "cu"],
["Kingston", "Jamaika", "jm"],
["Santo Domingo", "Dominikanische Republik", "do"],
["Port-au-Prince", "Haiti", "ht"],
["San José", "Costa Rica", "cr"],
["Panama-Stadt", "Panama", "pa"],
["Guatemala-Stadt", "Guatemala", "gt"],
["San Salvador", "El Salvador", "sv"],
["Managua", "Nicaragua", "ni"],
["Tegucigalpa", "Honduras", "hn"],
["La Paz", "Bolivien", "bo"],
["Quito", "Ecuador", "ec"],
["Montevideo", "Uruguay", "uy"],
["Asunción", "Paraguay", "py"],
["Malabo", "Äquatorialguinea", "gq"],

]
