const questions = [

    {
        "question": "Berlin ist die Hauptstadt welchen Landes?",
        "answer_1": "Frankreich",
        "answer_2": "Spanien",
        "answer_3": "Deutschland",
        "answer_4": "Italien",
        "right_answer": "3",
    }

]

const capital_country_pairs = [
    {
        "Berlin": "Deutschland",
        "Paris": "Frankreich",
        "Madrid": "Spanien",
        "Rom": "Italien",
        "Wien": "Österreich",
        "Bern": "Schweiz",
        "Amsterdam": "Niederlande",
        "Brüssel": "Belgien",
        "Kopenhagen": "Dänemark",
        "Oslo": "Norwegen",
        "Stockholm": "Schweden",
        "Helsinki": "Finnland",
        "Athen": "Griechenland",
        "Lissabon": "Portugal",
        "Dublin": "Irland",
        "Prag": "Tschechien",
        "Warschau": "Polen",
        "Budapest": "Ungarn",
        "Sofia": "Bulgarien",
        "Bukarest": "Rumänien",
        "Zagreb": "Kroatien",
        "Sarajevo": "Bosnien und Herzegowina",
        "Belgrad": "Serbien",
        "Skopje": "Nordmazedonien",
        "Tirana": "Albanien",
        "Podgorica": "Montenegro",
        "Ljubljana": "Slowenien",
        "Bratislava": "Slowakei",
        "Reykjavik": "Island",
        "Tallinn": "Estland",
        "Riga": "Lettland",
        "Vilnius": "Litauen",
        "Valletta": "Malta",
        "London": "Vereinigtes Königreich",
        "Moskau": "Russland",
        "Kiew": "Ukraine",
        "Minsk": "Weißrussland",
        "Ankara": "Türkei",
        "Washington: D.C.": "USA",
        "Ottawa": "Kanada",
        "Mexiko-Stadt": "Mexiko",
        "Brasília": "Brasilien",
        "Buenos Aires": "Argentinien",
        "Santiago": "Chile",
        "Bogotá": "Kolumbien",
        "Lima": "Peru",
        "Caracas": "Venezuela",
        "Canberra": "Australien",
        "Wellington": "Neuseeland",
        "Peking": "China",
        "Neu-Delhi": "Indien",
        "Tokio": "Japan",
        "Seoul": "Südkorea",
        "Bangkok": "Thailand",
        "Jakarta": "Indonesien",
        "Hanoi": "Vietnam",
        "Kuala Lumpur": "Malaysia",
        "Singapur": "Singapur",
        "Manila": "Philippinen",
        "Riad": "Saudi-Arabien",
        "Abu Dhabi": "VAE",
        "Doha": "Katar",
        "Teheran": "Iran",
        "Bagdad": "Irak",
        "Damaskus": "Syrien",
        "Amman": "Jordanien",
        "Kairo": "Ägypten",
        "Addis Abeba": "Äthiopien",
        "Nairobi": "Kenia",
        "Pretoria": "Südafrika",
        "Accra": "Ghana",
        "Dakar": "Senegal",
        "Algier": "Algerien",
        "Tunis": "Tunesien",
        "Rabat": "Marokko",
        "Tripolis": "Libyen",
        "Khartum": "Sudan",
        "Luanda": "Angola",
        "Kinshasa": "Kongo",
        "Harare": "Simbabwe",
        "Kampala": "Uganda",
        "Maputo": "Mosambik",
        "Antananarivo": "Madagaskar",
        "Suva": "Fidschi",
        "Port Moresby": "Papua-Neuguinea",
        "Nassau": "Bahamas",
        "Havanna": "Kuba",
        "Kingston": "Jamaika",
        "Santo Domingo": "Dominikanische Republik",
        "Port-au-Prince": "Haiti",
        "San José": "Costa Rica",
        "Panama-Stadt": "Panama",
        "Guatemala-Stadt": "Guatemala",
        "San Salvador": "El Salvador",
        "Managua": "Nicaragua",
        "Tegucigalpa": "Honduras",
        "La Paz": "Bolivien",
        "Quito": "Ecuador",
        "Montevideo": "Uruguay",
        "Asunción": "Paraguay",
        "Malabo": "Äquatorialguinea",
    }
]